### ISSUE TITLE
(It is important to note that we have ran "chmod -R 777 /etc/profile.d/")

### ISSUE THREAD

**Issue by rany2** [cobwebdev/celos#1]
Does this mean CelOS has unsafe permissions for /etc/profile.d or am I misunderstanding?

The title is from the README

**Comment by cobwebdev** [comment]
It means that any script ran in this directory will be able to execute commands with "sudo" privileges. Unless you place a malicious script in this directory yourself, it should be safe.

If any future vulnerabilities are found we will re-open this issue, but for now both I (Adam Salt) and the rest of the Cob:web Development team have agreed that this should not be any cause for alarm.

Thank you
- Adam Salt, Cob:web Lead.

**Comment by rany2** [comment]
@cobwebdev But does this mean that CelOS has 777 permissions for `/etc/profile.d` or is this needed for making the ISO only?

**Comment by cobwebdev** [comment]
We will look into this, I'll reopen the issue for the moment, thank you.

**Comment by cobwebdev** [comment]
We are going to try giving the file /etc/profile.d/apply-theme.sh 777 permissions rather than the entire folder. We've identified a potential vulnerability due to giving the folder 777 permissions. If a script is downloaded, it could install a malicious script to /etc/profile.d/ which will be executed with 777 permissions on the next user login. 

We will give the file "apply-theme.sh" 777 permissions since it will be unable to be tampered with, and will only be ran once before self-deleting. We will see if this works in CelOS 1 [Beta v1.1.1], thank you for bringing this issue to our attention.

We will update you with the results.

- Adam Salt, 
CelOS Lead Developer & Cob:web Lead.

**Comment by rany2** [comment]
Not sure if this is what you mean to do: https://github.com/cobwebdev/celos/pull/2

P.S you might want only accounts in "user" group running this script

**Comment by cobwebdev** [comment]
We currently only mean to have the script run once on login, thank you for creating a PR.
`flatpak update -y` is ran so that the adwaita-dark theme is applied to all flatpak applications immediately during login.

**Comment by rany2** [comment]
I'm against having `flatpak update -y` because most devices are on wifi and the user doesn't have the opportunity to connect to internet yet. Also it would make logging in much slower than it needs to be because of downloading updates+new package.

Perhaps using https://github.com/refi64/pakitheme would be better (doesn't need wifi)

**Comment by cobwebdev** [comment]
I've implemented your changes, I'll see what I can do. 
Thank you :)

**Comment by whyadamsalt** [comment]
This file has since been removed from CelOS as it is no-longer needed. We now use Gnome-session rather than Ubuntu-session and so all of the default values are enabled by default.
